import { Box, CssBaseline, ThemeProvider } from "@mui/material"
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter"
import { setTheme } from "@web/actions"
import { InitialColorSchemeScript, themes } from "@web/theme"
import type { Metadata } from "next"
import { cookies } from "next/headers"
import { PropsWithChildren } from "react"
import { ThemeVariant, darkTheme, lightTheme } from "../theme/theme"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({ children }: PropsWithChildren) {
  const usrCookies = cookies()
  const userTheme = usrCookies.get("app-theme")
  const themeKey = String(userTheme)
  const hasTheme = Object.hasOwn(themes, themeKey)
  if (!hasTheme) {
    // await setTheme("light")
  }
  return (
    <html lang="ru">
      <InitialColorSchemeScript />
      <AppRouterCacheProvider options={{ key: "css", prepend: true }}>
        <ThemeProvider theme={darkTheme}>
          <Box
            component="body"
            sx={{
              display: "flex",
              flexDirection: "column",
              minHeight: "100vh",
            }}
          >
            {children}
          </Box>
          <CssBaseline />
        </ThemeProvider>
      </AppRouterCacheProvider>
    </html>
  )
}
